In [3]:
import numpy as np

In [4]:
width=5
height=5
sigma=1

In [11]:
w_h=int((width-1)/2)
h_h=int((height-1)/2)
pi=np.pi
a=np.array([[x**2+y**2 for x in range(-w_h,w_h+1)] for y in range(-h_h, h_h+1)])
GaussianMatrix=1/(2*pi*sigma**2)*np.exp(-a/(2*sigma**2))

In [12]:
print(GaussianMatrix)

[[ 0.00291502  0.01306423  0.02153928  0.01306423  0.00291502]
 [ 0.01306423  0.05854983  0.09653235  0.05854983  0.01306423]
 [ 0.02153928  0.09653235  0.15915494  0.09653235  0.02153928]
 [ 0.01306423  0.05854983  0.09653235  0.05854983  0.01306423]
 [ 0.00291502  0.01306423  0.02153928  0.01306423  0.00291502]]
